### PR TITLE
fix overflow by removing unnecessary .from(height:

### LINKED ISSUE #102: Footer Display Issues
On ios (at least)...

- [ ] When content is too big, footer gets compressed so that text disappears and can't use "Derive a secret"
- [ ] In dark mode, derive a secret should be white when not selected and dark otherwise, but it is inverted
- [ ] Once selected, the Derive a Secret icons won't re-open the menu (only the text will)

IMG_0048

### PR DESCRIPTION
**Pull request by UppaJung**
fixes #102

### CODE REVIEW

File: DiceKeys/Views/DiceKey/DerivedFromDiceKey.swift [hunk 1]
```diff
@@ -57,41 +57,37 @@ struct DerivedFromDiceKey<Content: View>: View {
...
+                        .offset(x: 0, y: -funnelBottomPadding )
 //                        Text("ContentHight: \(contentHeight), fh:\(totalFunnelHeight) height: \(totalHeight)").foregroundColor(.red).background(Color.black)
-                    }.if(aspectRatio != nil) { $0.frame(height: funnelHeight + contentHeight) }
-                }.if(aspectRatio != nil) { $0.frame(height: totalHeight) }
-//            Spacer()
-//        }
-    }.if(aspectRatio != nil) { $0.frame(height: frameHeight).aspectRatio(aspectRatio, contentMode: .fit) }
+                }.if(aspectRatio != nil) { $0.frame(height: funnelHeight + contentHeight) }
+            }
+    }.if(aspectRatio != nil) { $0.aspectRatio(aspectRatio, contentMode: .fit) }
```
Comment (UppaJung) [inline DiceKeys/Views/DiceKey/DerivedFromDiceKey.swift:90]: It's hard to see because of the reformatting, but it's the removal of the frame height in what are now lines 89 and 90 that fix this.
